-   id: add-msg-issue-suffix
    name: Add issue as commit message suffix
    description: Searches the branch name for something looking like a jira issue's name and apends the commit message with it
    entry: add-msg-issue-sufix
    language: python
    always_run: true
    stages: [prepare-commit-msg]
